### ISSUE TITLE
[FEATURE] Extend support for C++ version < 17

### ISSUE THREAD

**Issue by DebadityaPal** [hs2361/k-means-compressor#5]
Currently, we don't know the exact reason for this version dependency however, it might be related to the filesystems library in C++ being used by [BatchCompressor.hpp](https://github.com/hs2361/k-means-compressor/blob/dbe7d5473997176c41d4dd82a285e32159f522fe/BatchCompressor.hpp)
Please help us figure out the reason behind this and help us solve this dependency.
Backwards compatibility is a major issue.

**Comment by XDRAGON2002** [comment]
I have tested the application on various versions and this is what I found - 

**11.1.0** - 
Works exactly as expected.

**9.3.1** - 
Works exactly as expected.

**8.1.0** - 
Does not compile due to bug in the <filesystem> library, this is because before V8 the <filesystem> library was actually a part of the <experimental/filesystem> library and for resolving scope std::experimental::filesystem had to be used, in V8 the library was switched to its own standalone header but due to some bugs the feature could not be used as expected. This was later patched in V9.
References - 
https://sourceforge.net/p/mingw-w64/bugs/737/
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78870
https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=b02923592a55b52d796656c5b4f34a964a2604a9
https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=9534a5e62dc2b81d001f98f1ed582bc3f1d39c80

**7.5.0** -
Does not compile as it is unable to resolve <filesystem> inclusion because in this version the library was part of <experimental/filesystem> and the std::experimental::filesystem scope resolution had to be used along with it.
Moreover, <experimental/filesystem> was not always part of the default compiler installation package and hence had to be installed seperately (arguments had to passed to the linker while compiling).
But, once these changes have been made while compiling, it should work as expected.

**Comment by hs2361** [comment]
Yes, that sounds about right. The <experimental/filesystem> we're using for traversing directories is a C++17 feature, which is why older versions of gcc have trouble compiling the program.

**Comment by XDRAGON2002** [comment]
So, I feel that this issue is actually a compiler specific issue, so we should just put this in the documentation as a "supported versions" section ?
As the only other thing we can do is define macros to either select <filesystem> or <experimental/filesystem> for defining the scope of "fs".

**Comment by XDRAGON2002** [comment]
I am actually updating the documentation regarding #8 so if this issue is assigned to me as well I can finish up the writeup for both the issues with a single PR. So should I go ahead with it ?

**Comment by XDRAGON2002** [comment]
Any updates on what should be done with this issue ?

**Comment by DebadityaPal** [comment]
Like @hs2361 said, this seems to be a compiler issue with the `filesystems` header. However, older compilers do support the header but it falls under `experimental::filesystems`. So, you can try adding version checks in the appropriate places and load the header accordingly.
This is a good resource for reading into this problem: [https://stackoverflow.com/questions/53365538/how-to-determine-whether-to-use-filesystem-or-experimental-filesystem](https://stackoverflow.com/questions/53365538/how-to-determine-whether-to-use-filesystem-or-experimental-filesystem)

**Comment by XDRAGON2002** [comment]
I will work on this then.

**Comment by XDRAGON2002** [comment]
Opened PR #13 that fixes this issue.
